---
# See https://github.com/ansible/devtools/blob/main/.github/workflows/push.yml
name: push
on:
  push:
    branches:
      - master
      - "releases/**"
      - "stable/**"

jobs:
  ack:
    uses: ansible/devtools/.github/workflows/push.yml@main
